### ISSUE TITLE
SPI detailed requests updating

### ISSUE THREAD

**Issue by erkuo521** [Aceinna/docs_aceinna-dmu380#17]
I think below SPI points need to be mentioned to customer:

- update Timing Requirements limitations for different unit: 300, 330, 383.....,, 

- slave of IMU is 80/120/140Mhz have different limitation to Timing, so do we have request to Master side?  if yes, should specified in Manual

**Comment by AndreyBondarev** [comment]
Its already specified. Please provide link to exact page

**Comment by erkuo521** [comment]
thanks a lot.
