### ISSUE TITLE
330BI---PCB design interface updating for customer application

### ISSUE THREAD

**Issue by erkuo521** [Aceinna/docs_aceinna-dmu380#18]
in position 330: Docs » OpenIMU Modules » OpenIMU330BI 
we need to add more information to support cusotmer as below pic.

![image](https://user-images.githubusercontent.com/48200666/68636090-68ed2900-0535-11ea-9a60-5a70bfc2b879.png)

**Comment by kravi20** [comment]
@erkuo521 what kind of Information do you need to for this pic. please send me the info, so I can update the page.

**Comment by erkuo521** [comment]
As above area, we need to add below information:(also mentioned in email)
- Top and bottom view of pin layout to avoid misunderstanding in customer side.
- Change the above pin assignment to below detailed pic

**Comment by kravi20** [comment]
I updated it with the pics
