### ISSUE TITLE
missing information about default filter setting with OpenIMU300RI

### ISSUE THREAD

**Issue by yifanff** [Aceinna/docs_aceinna-dmu380#20]
Missing information about default filter setting with OpenIMU300RI, compared with MTLT305D,  Acceleration sensor Filter default is 5 Hz. Rate Sensor default is 25 Hz.

**Comment by yifanff** [comment]
QA need the information default filter setting to go through data performance factory test.

**Comment by joem-at-aceinna** [comment]
For the IMU, the default settings for the filters are:
    Prefilter: 50 Hz
    User-filter: 25 Hz

The application will also dictate the user-filter settings.  The MTLT and VG should have the accelerometer user-filter cutoff set to 5 Hz.  The rate-sensor filter should remain at 25 Hz.

**Comment by yifanff** [comment]
@joem-at-aceinna Hi Joe, thanks for your comments!
