### ISSUE TITLE
the temperature formula should be update

### ISSUE THREAD

**Issue by yifanff** [Aceinna/docs_aceinna-dmu380#23]

**Comment by AndreyBondarev** [comment]
What platform, what application, what interface?

**Comment by yifanff** [comment]
Platform:OpenIMU300ZI, OpenIMU330BI.
application: IMU
Interface: SPI

**Comment by AndreyBondarev** [comment]
Formula provided on this page is accurate:
https://openimu.readthedocs.io/en/latest/software/SPImessaging.html
It corresponds to conversion in function  void FillSPIBurstDataBuffer() which implemented in file UserCommunicationSPI.c or UserMessagingSPI.c

**Comment by yifanff** [comment]
Thanks.
