### ISSUE TITLE
OPENIMU330BI - *Error* in OpenIMU330BI_Pin_Definition.xlsx

### ISSUE THREAD

**Issue by erkuo521** [Aceinna/docs_aceinna-dmu380#24]
"OpenIMU330BI module top view of package" - this is incorrect, it is a **BOTTOM** side view.
below points need to be updated:
![Snipaste_2019-12-13_09-31-58](https://user-images.githubusercontent.com/48200666/70762503-b4d8fb00-1d8b-11ea-9914-ad06a9d2ed24.png)

**Comment by AndreyBondarev** [comment]
Done
