### ISSUE TITLE
300RI the Picture broken(Base folder from VScode CAN J1939 Workspace)

### ISSUE THREAD

**Issue by yifanff** [Aceinna/docs_aceinna-dmu380#31]
![2019-12-22_21h53_17](https://user-images.githubusercontent.com/5958693/71495448-d3112180-2888-11ea-9d9b-58f34a533541.jpg)

**Comment by kravi20** [comment]
Fixed Picture link OpenIMU300RI-CAN_J1939_Project and pushed the changes.
