### ISSUE TITLE
does the SPI section support both the openimu300 and openimu330

### ISSUE THREAD

**Issue by yifanff** [Aceinna/docs_aceinna-dmu380#4]
Does the all SPI description compatible with openimu300 and openimu330 SPI interface?  That point should be clarified in the document.

**Comment by AndreyBondarev** [comment]
So far there is no section for OpenIMU330 in the document yet. But interface will be the same for both

**Comment by m5horton** [comment]
There is now included on both 330BI and 300ZI.  See here

https://openimu.readthedocs.io/en/latest/software/SPImessaging.html
