### ISSUE TITLE
How to differentiate on unit via SPI interface 

### ISSUE THREAD

**Issue by yifanff** [Aceinna/docs_aceinna-dmu380#7]
As for openimu300 and openimu330 unit, How to differentiate units via SPI interface?  though  modelstring could be read through UART interface to differentiate units, It seems no unit ID could be read through SPI interface.

**Comment by AndreyBondarev** [comment]
Table1 in the SPI engine description updated to include corresponding registers. Also since it's open source customers may implement their own mechanism of unit identification

**Comment by yifanff** [comment]
Ok, thanks. In the updated register map, why there are two OpenIMU330 words left?  what is the default Product ID with factory released FW currently?

**Comment by AndreyBondarev** [comment]
Thanks for the good catch - fixed

**Comment by yifanff** [comment]
Ok，thanks，what is default product ID via SPI interface currently?

**Comment by AndreyBondarev** [comment]
Default ID on OpenIMU300 is 0x3000 and on OpenIMU330 0x3300 (on SPI interface)

**Comment by yifanff** [comment]
thanks! : )
