### ISSUE TITLE
Documentation for OpenIMU300ZA EVK is missing

### ISSUE THREAD

**Issue by osjacky430** [Aceinna/docs_aceinna-dmu380#9]
Hi, as the title has said, recently, I found that the documentation for openIMU300ZA EVK does not exist, [this pinout website]( https://openimu.readthedocs.io/en/latest/300ZA/pinout.html) tells me that the page doesn't exist. Is it intended or not? I've just bought the EVK few days ago, and I am wondering the pinout, if it is identical to other imu products, please make the link direct to those pages, thank you!

**Comment by dxg-aceinna** [comment]
The unit is renamed to OpenIMU300ZI. You can find the pinout here: https://openimu.readthedocs.io/en/latest/300ZI/pinout.html
